from decimal import Decimal
from typing import List

from item import Item


class ElectronicItem(Item):
    def __init__(self, title: str, desc: str, price: Decimal, weight: float,
                 seller: str, electronic_type: str, model: str,
                 dimensions: List[int]):
        super().__init__(title, desc, price, weight, seller)

        # Private instance attributes
        self._electronic_type: str = electronic_type
        self._model: str = model
        self._dimensions: List[int] = dimensions

    def get_electronic_type(self) -> str:
        return self._electronic_type

    def get_model(self) -> str:
        return self._model

    def get_dimensions(self) -> List[int]:
        return self._dimensions

    @classmethod
    def add_item(cls, electronic: ElectronicItem) -> type(None):
        # create electronic dict that will be added to the database
        # id will be generated by mongo
        electronic = {
            'title': electronic.get_title(),
            'description': electronic.get_desc(),
            'price': electronic.get_price(),
            'weight': electronic.get_weight(),
            'seller': electronic.get_seller(),
            'electronic_type': electronic.get_electronic_type(),
            'model': electronic.get_model(),
            'dimensions': electronic.get_dimensions()
        }

        # making insertion
        electronic_col.insert_one(electronic)
        