from decimal import Decimal
from typing import List

from item import Item
from clothing_item import ClothingGender

import pymongo

# establish connection with database
myclient = pymongo.MongoClient('mongodb://localhost:27017/')
# create the databse if it doesn't already exist
db = myclient.exchange4students

# create sports gear collection if it doesn't already exist
sports_gear_col = db.sports_gear


class SportsGearItem(Item):
    def __init__(self, item_id: str, title: str, desc: str, price: Decimal,
                 weight: float, seller: str, gear_type: str, size: str,
                 gender: ClothingGender):
        super().__init__(item_id, title, desc, price, weight, seller)

        # Private instance attributes
        self._gear_type: str = gear_type
        self._size: str = size
        self._gender: ClothingGender = gender

    def get_gear_type(self) -> str:
        return self._gear_type

    def get_size(self) -> str:
        return self._size

    def get_gender(self) -> List[int]:
        return self._gender

    @classmethod
    def add_sports_gear(cls, title: str, desc: str, price: Decimal,
                        weight: float, seller: str, gear_type: str, size: str,
                        gender: ClothingGender):
        # create sports_gear dict that will be added to the database
        # id will be generated by mongo
        sports_gear = {
            'title': title,
            'description': desc,
            'price': price,
            'weight': weight,
            'seller': seller,
            'gear_type': gear_type,
            'size': size,
            'gender': gender
        }

        # making insertion
        inserted_sports_gear = sports_gear_col.insert_one(sports_gear)
        # not sure what needs to be returned here?
        return inserted_sports_gear
