name: CI Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
             
            - name: Install black
              run: pip3 install black
            
            - name: Enforce formatting with yapf
              run: python3 -m black --check

            - name: Install pylint
              run: pip3 install pylint

            - name: Enforce best practices with pylint
              run: python3 -m pylint **/*.py

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Install dependencies
              run: pip3 install -r requirements.txt

            - name: Test
              run: | 
                cd src/tests 
                python3 main.py
